# Common settings
experiment:
  data_root_path: ./src/pkgs/datasets/test_dataset
  modeldataset_type: cnn  # transformer | cnn | patch1d | patch2d | two

  train_config:
    max_epochs: 50
    optimizer: adamw  # adamw 
    scheduler: step  # step | plateau

  mlflow_config:
    tracking_uri: "file:./mlruns"
    experiment_name: experiment_name

  modeldataset_config:
    image_height: 224
    image_width: 224
    num_classes: 3 # 2 | 3
    lr: 0.0001
    criterion: cross_entropy  # cross_entropy | dice
    metric: binary_jaccard  
    batch_size: 4

    data_augmentation_config:
      vertical_flip: True
      horizontal_flip: True
      random_brightness_contrast: True

    # Model and dataset specific settings
    # If model_dataset_type is model_dataset_type = patch, you need to set patch_setting
    patch1d_setting:
      patch_size: 4
    
    patch2d_setting:
      patch_size: 32
      backborn: mobilenet_v2

    # If model_dataset_type is model_dataset_type = two, you need to set two_setting
    two_setting:
      two_size: 4

    # If model_dataset_type is model_dataset_type = transformer, you need to set transformer_setting
    transformer_setting:
      pretrained_model: nvidia/segformer-b5-finetuned-cityscapes-1024-1024

    # If model_dataset_type is model_dataset_type = cnn, you need to set cnn_setting
    cnn_setting:
      backborn: mobilenet_v2
      task: all  # plant | crop | all
